services:
  llh:
    image: intellistream/llh:devel-ubuntu22.04
    environment:
      - CUDACXX=/usr/local/cuda/bin/nvcc
      - NVIDIA_VISIBLE_DEVICES=all  # Expose all GPUs (optional)
    volumes:
      - "../..:/workspace"  # Mount a host directory to /workspace
    working_dir: /workspace        # Set the default working directory
    entrypoint: /usr/sbin/sshd -D  # Start SSH server
    stdin_open: true               # Keep STDIN open for interactive debugging
    tty: true                      # Enable a pseudo-TTY
    ports:
      - "2222:22"                  # Map SSH port to host
