name: CMake

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]
env:
  BUILD_TYPE: Release

jobs:
  format:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set Permission for clang-format Script
        run: chmod +x ./scripts/run-clang-format.sh

      - name: Install clang-format
        run: sudo apt-get install clang-format -y

      - name: Run clang-format
        run: ./scripts/run-clang-format.sh

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Automatically formatted code using clang-format"
          branch: ${{ github.head_ref }}
          file_pattern: '*.hpp *.cpp *.c *.h'

  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Install toolchains
        run: |
          sudo apt-get update
          sudo apt install gcc-11 g++-11
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 11
          sudo apt install gcc g++ cmake python3 pip libboost-dev libboost-all-dev python3-dev
      - name: Install torch
        run: |
          sudo pip3 install torch==2.4.0 torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        env:
          CC: gcc
          CXX: g++

      - name: List Build Directory Contents
        run: ls -la ${{github.workspace}}/build

      - name: Check if Tests are Detected
        working-directory: ${{github.workspace}}/build
        run: ctest --show-only

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure

