name: CMake

on:
  push:
    branches: [ main,chore/format ]

  pull_request:
    branches: [ main ]
env:
  BUILD_TYPE: Release

jobs:
  format:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Set Permission for clang-format Script
        run: chmod +x ./scripts/run-clang-format.sh

      - name: Install clang-format
        run: sudo apt-get install clang-format-11

      - name: Run clang-format
        run: ./scripts/run-clang-format.sh

      - name: shopt to enable globstar
        run: shopt -s globstar

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Automatically formatted code using clang-format"
          branch: ${{ github.head_ref }}
          file_pattern: '*.hpp *.cpp *.h *.c'
