name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install liblog4cxx
        run: sudo apt-get install -y liblog4cxx-dev

      - name: Install g++-11
        run: |
          sudo apt-get update
          sudo apt install gcc-11 g++-11
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 11

      - name: Initialize and update submodules
        run: git submodule update --init --recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        env:
          CC: gcc-11
          CXX: g++-11

      - name: List Build Directory Contents
        run: ls -la ${{github.workspace}}/build

      - name: Check if Tests are Detected
        working-directory: ${{github.workspace}}/build
        run: ctest --show-only

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure